### ISSUE TITLE
CoinExchange is closed

### ISSUE THREAD

**Issue by fanatikhamsi** [dougdellolio/crypto-arbitrage-csharp#9]
CoinExchange and api is closed. 
crypto-arbitrage-csharp/CryptoArbitrageSharp/ArbitrageClient.cs line 32
`var krakenExchange = new CoinExchangeExchange(httpClient, httpRequestMessageService, currencyPairService);`
replace
`var krakenExchange = new KrakenExchange(httpClient, httpRequestMessageService, currencyPairService);`

**Comment by dougdellolio** [comment]
thanks. fixed with https://github.com/dougdellolio/crypto-arbitrage-csharp/pull/10
